remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Shary
logo: /Assets/Img/7ABC3E2B-1259-42B1-98E6-F9B50092520F.png
description: Ya'll got too much stuff.
